# Generated by Django 4.1.5 on 2023-08-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id_langue', models.AutoField(primary_key=True, serialize=False)),
                ('libelleLangue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.langue')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
